/**
 * adminService.js — User Management API requests
 */
import api from './api';

export const adminService = {
  /**
   * List all users (supports optional search and isActive filters)
   */
  getUsersList: async (searchTerm = '', isActive = null) => {
    const params = {};
    if (searchTerm) params.search = searchTerm;
    if (isActive !== null) params.isActive = isActive;
    
    const response = await api.get('/admin/users', { params });
    return response.data;
  },

  /**
   * Get details for a single user
   */
  getUserById: async (id) => {
    const response = await api.get(`/admin/users/${id}`);
    return response.data;
  },

  /**
   * Create a new user (with temp password generated by backend)
   * @param {{ name, email, roleId }} payload
   */
  createUserByAdmin: async (payload) => {
    const response = await api.post('/admin/users', payload);
    return response.data;
  },

  /**
   * Update a user's role
   */
  updateUserRole: async (id, roleId) => {
    const response = await api.patch(`/admin/users/${id}/role`, { roleId });
    return response.data;
  },

  /**
   * Deactivate a user
   */
  deactivateUser: async (id) => {
    const response = await api.patch(`/admin/users/${id}/deactivate`);
    return response.data;
  },
};

export default adminService;
